### ISSUE TITLE
User defined function errors

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#32]
Running a function on products : sum on a column of the last released for a product, the WS do not return any content and the front probably does not handle it, the running button is still loading, there is a console error TypeError: a.first(...) is undefined; possible reason : every part link to the product does not have the selected column.
The same on a sum on an existing number column of the last released for a product, for a decimal value, the resultat is approximate (for a part of with value 18, and a part with value 0.1, the result of the sum is 18.200000000000003; after adding another part of 0.1, the result became 18.300000000000004)

**Comment by mguimard** [comment]
These are two distinct bugs. The first one has already a dedicated issue.

The second one is more problematic and is well known in computer science and js. This should be fixed in the UI code. Also, we could ask to the user which precision he wants.

More infos here
http://javascript.info/number#imprecise-calculations
